### ISSUE TITLE
Integration into official rubygems?

### ISSUE THREAD

**Issue by ghost** [rdp/specific_install#35]
Hey there,

Feel free to close this issue at any time.

I had a look at the functionality and it seems to be a useful addition.

Bundler allows this as far as I know already whereas rubygem does
not allow github-based installation, I think (from the gem commandline).

So I was wondering, have you asked the rubygem core team whether
they would like to integrate it; and of course, before that, would you
even want to have this functionality included into rubygems itself?

**Comment by rdp** [comment]
I might be afraid of the maintenance LOL...hmm...it does work already as a
plugin hmm...I guess you're welcome to bring it up with them :D

**Comment by rdp** [comment]
It's kind of there in bundler these days I suppose..feel free to propose some stuff upstream though! :)
