### ISSUE TITLE
Version 2.3.4 broke ref install

### ISSUE THREAD

**Issue by mikeweaver** [rdp/specific_install#45]
2.3.3 works, 2.3.4 fails with error:

fatal: not a git repository (or any of the parent directories): .git
ERROR:  While executing gem ... (RuntimeError)
    '$ git reset --hard 7d85a61271bf4722aaecc81b8ab97152a40e60a8' exited with an error

**Comment by rdp** [comment]
could you try with 2.3.5 for me?

**Comment by mikeweaver** [comment]
That worked! Thanks for the quick response!
