### ISSUE TITLE
"undefined method `exists?' for File:Class" in Ruby v3

### ISSUE THREAD

**Issue by astencel-sumo** [rdp/specific_install#58]
Hi @rdp and thanks for this great gem. We have been using it as part of our open source collection software at @SumoLogic for some time now: https://github.com/SumoLogic/sumologic-kubernetes-fluentd/blob/v1.14.6-sumo-5/Dockerfile#L32.

Now we want to start using Ruby v3 and I'm getting the `undefined method exists? for File:Class`, which has apparently just been [fixed](https://github.com/rdp/specific_install/pull/57). I think we need a new release of the gem to use it. Can you make it please?

Again, thanks for your work on this gem. Let me know if I can help in any way.

**Comment by rdp** [comment]
Thanks for the kind words, give it a shot!

**Comment by davidrunger** [comment]
I'm not the OP, but the new release (0.3.8) works for me with Ruby 3.2.0 (whereas 0.3.7 was not working for me with Ruby 3.2.0).

Thank you, @rdp !

**Comment by astencel-sumo** [comment]
Thank you so much @rdp for the prompt release :pray: It works for me too :tada:
